config/routes.rb
GetMedia::Application.routes.draw do
 
  get 'users/confirm'

  get 'downloads/remote'

  resources :users
  resources :downloads
  resources :collectors, only: [ :index, :show, :update ]
  resources :sessions, only: [ :new, :create, :destroy, :index ]

  root :to             => 'static_pages#index'

  match '/about', :to  => 'static_pages#about'
  match '/faq', :to    => 'static_pages#faq'
  match '/login', :to  => 'static_pages#login'
  match '/logout', :to => 'sessions#destroy', :via => :delete

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GetMedia - <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <div class="modal fade" id="ajax-error">
    <div class="modal-header">
      <button class="close" data-dismiss="modal">&times;</button>
      <h3>Error</h3>
    </div>
    <div class="modal-body">
      <p></p>
    </div>
  </div>
  <div class="ajax-progress"></div>
  <header class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "GetMedia", root_path, class: "brand" %>
        <nav>
          <ul class="nav pull-right">
            <% if signed_in? %>
              <li<%= current_page?(downloads_path) ? " class='active'" : nil %>><%= link_to "Downloads", downloads_path %></li>
              <% if current_user.is_admin? %>
                <li<%= current_page?(users_path) ? " class='active'" : nil %>><%= link_to "Users", users_path %></li>
                <li<%= current_page?(collectors_path) ? " class='active'" : nil %>><%= link_to "Collectors", collectors_path %></li>
              <% end %>
              <li><%= link_to "Logout", logout_path, method: "delete" %></li>
            <% else %>
              <!-- TOFIX! Doble qoutes instead of single ones -->
              <!-- TOFIX! Hack with login_path check, because of /sessions and /users URIs in case of failed login/register -->
              <li<%= !current_page?(about_path) &&
                     !current_page?(faq_path) ? " class='active'" : nil %>><%= link_to "Login", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>">
        <a class="close" data-dismiss="alert">&times;</a>
        <%= value %>
      </div>
    <% end %>
    <div class="hero-unit">
      <%= yield %>
    </div>
  </div>
  <footer>
    <div class="container">
      <ul class="nav nav-pills">
        <li<%= current_page?(about_path) ? " class='active'" : nil %>><%= link_to "About Us", about_path %></li>
        <li<%= current_page?(faq_path) ? " class='active'" : nil %>><%= link_to "FAQ", faq_path %></li>
      </ul>
    </div>
  </footer>
</body>
</html>